apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-project-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/hashan-7/devops-with-kubernetes-2026.git'
    targetRevision: HEAD
    path: todo-app/manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true