apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-logs
          emptyDir: {}
      containers:

        - name: log-writer
          image: log-output:v1
          imagePullPolicy: IfNotPresent
          command: ["java", "-cp", "app.jar", "com.example.Writer"]
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/files

        - name: log-reader
          image: log-output:v1
          imagePullPolicy: IfNotPresent
          command: ["java", "-cp", "app.jar", "com.example.Reader"]
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/files