apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: log-output-config
      containers:
        - name: log-output
          image: hashan7/log-output:v5.5
          imagePullPolicy: IfNotPresent
          command: ["java", "-cp", "app.jar", "com.example.Main"]
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: MESSAGE
          volumeMounts:
            - name: config-volume
              mountPath: /config

          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 8080