apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pingpong
  namespace: exercises
spec:
  template:
    spec:
      containers:
        - name: ping-pong
          image: hashan7/ping-pong:v4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD