apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-backup-cronjob
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup-worker
              image: google/cloud-sdk:alpine
              env:
                - name: BUCKET_NAME
                  value: "dwk-todo-backups"
                - name: PGHOST
                  value: "postgres-svc"
                - name: PGUSER
                  value: "postgres"
                - name: PGDATABASE
                  value: "postgres"
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_PASSWORD
              volumeMounts:
                - name: google-cloud-key
                  mountPath: /var/secrets/google
                  readOnly: true
              command:
                - /bin/sh
                - -c
                - |
                  echo "=== STEP 1: Installing Postgres Client ==="
                  apk add --no-cache postgresql-client
                  
                  echo "=== STEP 2: Authenticating with Google Cloud ==="
                  gcloud auth activate-service-account --key-file=/var/secrets/google/key.json
                  
                  echo "=== STEP 3: Exporting Database Dump ==="
                  FILENAME="backup-$(date +%Y%m%d-%H%M%S).sql"
                  pg_dump -h $PGHOST -U $PGUSER -d $PGDATABASE > /tmp/$FILENAME
                  
                  echo "=== STEP 4: Uploading to Google Object Storage ==="
                  gsutil cp /tmp/$FILENAME gs://$BUCKET_NAME/$FILENAME
                  
                  echo "=== Backup Process Complete! ==="
          restartPolicy: OnFailure
          volumes:
            - name: google-cloud-key
              secret:
                secretName: storage-sa-key