apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: local-persistent-storage
          persistentVolumeClaim:
            claimName: shared-claim
      containers:
        - name: todo-app
          image: PROJECT/IMAGE
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: local-persistent-storage
              mountPath: /usr/src/app/files
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: PORT
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: BACKEND_URL
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "150m"
              memory: "128Mi"