FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=build /app/target/todo-app-1.0-SNAPSHOT.jar app.jar
CMD ["java", "-cp", "app.jar", "com.example.Main"]
