apiVersion: v1
kind: Service
metadata:
  name: todo-postgres-svc
  namespace: project
spec:
  ports:
    - port: 5432
      name: postgres
  clusterIP: None
  selector:
    app: todo-postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-postgres-ss
  namespace: project
spec:
  serviceName: todo-postgres-svc
  replicas: 1
  selector:
    matchLabels:
      app: todo-postgres
  template:
    metadata:
      labels:
        app: todo-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_DB
              value: "todos"
          volumeMounts:
            - name: todo-postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: todo-postgres-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: local-path
        resources:
          requests:
            storage: 250Mi