apiVersion: v1
kind: Service
metadata:
  name: wiki-svc
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: wiki
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki
  template:
    metadata:
      labels:
        app: wiki
    spec:
      volumes:
        - name: shared-data
          emptyDir: {}
      initContainers:
        - name: wiki-init
          image: alpine
          command: ['sh', '-c']
          args:
            - apk add --no-cache curl && curl -sL https://en.wikipedia.org/wiki/Kubernetes -o /usr/share/nginx/html/index.html
          volumeMounts:
            - name: shared-data
              mountPath: /usr/share/nginx/html
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: shared-data
              mountPath: /usr/share/nginx/html
        - name: wiki-sidecar
          image: alpine
          command: ['/bin/sh', '-c']
          args:
            - apk add --no-cache bash curl &&
              bash -c 'while true; do
              sleep $(( (RANDOM % 600) + 300 ));
              curl -sL https://en.wikipedia.org/wiki/Special:Random -o /usr/share/nginx/html/index.html;
              done'
          volumeMounts:
            - name: shared-data
              mountPath: /usr/share/nginx/html